# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfAlias < Formula
  desc "Create Cloudflare email alias' directly from your terminal or Alfred."
  homepage "https://github.com/dustinblackman/cf-alias"
  version "0.1.5"

  on_macos do
    url "https://github.com/dustinblackman/cf-alias/releases/download/v0.1.5/cf-alias_0.1.5_darwin_amd64.tar.gz"
    sha256 "9136436d75e2b15a9c05e86468401fdac7296d4b150a81ca3e6606c3cb44e169"

    def install
      # Install cf-alias
      bin.install "cf-alias"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "bash")
      (bash_completion/"cf-alias").write output

      output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "zsh")
      (zsh_completion/"_cf-alias").write output

      output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "fish")
      (fish_completion/"cf-alias.fish").write output
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the CfAlias
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/cf-alias/releases/download/v0.1.5/cf-alias_0.1.5_linux_amd64.tar.gz"
      sha256 "7637e0ebf78c5196a2d724267fd12a8d8ac1f3513b952036ce3819017dc52b3b"

      def install
        # Install cf-alias
        bin.install "cf-alias"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "bash")
        (bash_completion/"cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "zsh")
        (zsh_completion/"_cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "fish")
        (fish_completion/"cf-alias.fish").write output
      end
    end
  end

  test do
    system "#{bin}/cf-alias --version"
  end
end
