# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CfAlias < Formula
  desc "Create Cloudflare email alias' directly from your terminal or Alfred."
  homepage "https://github.com/dustinblackman/cf-alias"
  version "0.1.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dustinblackman/cf-alias/releases/download/v0.1.9/cf-alias_0.1.9_darwin_arm64.tar.gz"
      sha256 "f68541dedf1500bf961be73d281519309b5fbc38cdcec7f7c5febeaa40bb4943"

      def install
        # Install cf-alias
        bin.install "cf-alias"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "bash")
        (bash_completion/"cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "zsh")
        (zsh_completion/"_cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "fish")
        (fish_completion/"cf-alias.fish").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/cf-alias/releases/download/v0.1.9/cf-alias_0.1.9_darwin_amd64.tar.gz"
      sha256 "0a567c6827f668e8bbd733644eefdd543d7edea40419fe61532f3c7a05efa36a"

      def install
        # Install cf-alias
        bin.install "cf-alias"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "bash")
        (bash_completion/"cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "zsh")
        (zsh_completion/"_cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "fish")
        (fish_completion/"cf-alias.fish").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/cf-alias/releases/download/v0.1.9/cf-alias_0.1.9_linux_amd64.tar.gz"
      sha256 "446f221ccf2265b0e79f13502404e7150e8364a63bbb8e86993ffd373f715970"

      def install
        # Install cf-alias
        bin.install "cf-alias"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "bash")
        (bash_completion/"cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "zsh")
        (zsh_completion/"_cf-alias").write output

        output = Utils.safe_popen_read("#{bin}/cf-alias", "completion", "-s", "fish")
        (fish_completion/"cf-alias.fish").write output
      end
    end
  end

  test do
    system "#{bin}/cf-alias --version"
  end
end
