# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FetchHls < Formula
  desc "A quick and lazy solution to proxy HLS streams to external players (Chromecast, VLC)."
  homepage "https://github.com/dustinblackman/fetch-hls"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.1/fetch-hls_0.1.1_darwin_amd64.tar.gz"
    sha256 "7c2a248ef3fb9e55b77d9adbcd2e03e521756530b78ac091db95430be3454a08"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.1/fetch-hls_0.1.1_linux_amd64.tar.gz"
    sha256 "1583c1b0ba5875fddd913839fe2cc32cde0bbedc53791d495b531c81e6c320fa"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.1/fetch-hls_0.1.1_linux_armv6.tar.gz"
    sha256 "eeb3ab625a7af713596e896595589fcee333d2e200420e7cdb7b4d1099fd1fc8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.1/fetch-hls_0.1.1_linux_arm64.tar.gz"
    sha256 "2f9b61788a4031438fdf8dbd3cfa43b0d08bd971929ce43ab5af058db6c9b01e"
  end

  def install
    bin.install "fetch-hls"
  end

  test do
    system "#{bin}/fetch-hls --version"
  end
end
