# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FetchHls < Formula
  desc "A quick and lazy solution to proxy HLS streams to external players (Chromecast, VLC)."
  homepage "https://github.com/dustinblackman/fetch-hls"
  version "0.1.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.3/fetch-hls_0.1.3_darwin_amd64.tar.gz"
    sha256 "d91e0ef2f4085e3e2fd512be86e66d2b0c3490e3e349b4f93d37bba528f8b8f0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.3/fetch-hls_0.1.3_linux_amd64.tar.gz"
    sha256 "89c24669a5048ef80eb0d89a67db97b89f7f540bebea82498d874d1b345ad72c"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.3/fetch-hls_0.1.3_linux_armv6.tar.gz"
    sha256 "55fb873ca3c5472d7843719618674fea4890b1423ee94b9b33640f0dbc7808e6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dustinblackman/fetch-hls/releases/download/v0.1.3/fetch-hls_0.1.3_linux_arm64.tar.gz"
    sha256 "7da21da895b88f24d647fcd7f50c26c0234f75cf0912a9d2b9be226df0ab586e"
  end

  def install
    bin.install "fetch-hls"
  end

  test do
    system "#{bin}/fetch-hls --version"
  end
end
