# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomodrun < Formula
  desc "The forgotten go tool that executes and caches binaries"
  homepage "https://github.com/dustinblackman/gomodrun"
  version "0.4.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dustinblackman/gomodrun/releases/download/v0.4.4/gomodrun_0.4.4_darwin_amd64.tar.gz"
    sha256 "2cfd16dd4cc7530559c224218aafd560baf52a8c1988f15279349ce3028633e5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/dustinblackman/gomodrun/releases/download/v0.4.4/gomodrun_0.4.4_linux_amd64.tar.gz"
    sha256 "46d116f70fa8e1cdc2d3c957771cbf3e28a8e99993ac3587b26f82facd151b83"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/dustinblackman/gomodrun/releases/download/v0.4.4/gomodrun_0.4.4_linux_armv6.tar.gz"
    sha256 "176fd44c667ae4545fff6c4572cda14062a0b14837a689c04d95eeffe5f2cd48"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dustinblackman/gomodrun/releases/download/v0.4.4/gomodrun_0.4.4_linux_arm64.tar.gz"
    sha256 "a9acd5855e6efc02f98d3f306bc70c45ad9e5777fcedab4e0a61f1190c713634"
  end

  def install
    bin.install "gomodrun"
  end

  test do
    system "#{bin}/gomodrun --version"
  end
end
