# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LanguagetoolCodeComments < Formula
  desc "Integrates the LanguageTool API to parse, spell check, and correct the grammar of your code comments!"
  homepage "https://github.com/dustinblackman/languagetool-code-comments"
  version "0.3.0"

  on_macos do
    url "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.3.0/languagetool-code-comments_0.3.0_darwin_amd64.tar.gz"
    sha256 "11594ea66b5fb107266249526369b246b04bfc67d9b77c77413b2c87a66d0111"

    def install
      # Install languagetool-code-comments
      bin.install "languagetool-code-comments"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
      (bash_completion/"languagetool-code-comments").write output

      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
      (zsh_completion/"_languagetool-code-comments").write output

      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
      (fish_completion/"languagetool-code-comments.fish").write output
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the LanguagetoolCodeComments
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.3.0/languagetool-code-comments_0.3.0_linux_amd64.tar.gz"
      sha256 "9df50f860ab185729b64dcb03c4801f16416bbffacf67556d640f77986086384"

      def install
        # Install languagetool-code-comments
        bin.install "languagetool-code-comments"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
        (bash_completion/"languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
        (zsh_completion/"_languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
        (fish_completion/"languagetool-code-comments.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.3.0/languagetool-code-comments_0.3.0_linux_arm64.tar.gz"
      sha256 "19f6beb1ff1f14a317438928ab7a817c2ea879fd067fc2b7aad5bed3b024d714"

      def install
        # Install languagetool-code-comments
        bin.install "languagetool-code-comments"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
        (bash_completion/"languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
        (zsh_completion/"_languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
        (fish_completion/"languagetool-code-comments.fish").write output
      end
    end
  end

  test do
    system "#{bin}/languagetool-code-comments --version"
  end
end
