# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LanguagetoolCodeComments < Formula
  desc "Integrates the LanguageTool API to parse, spell check, and correct the grammar of your code comments!"
  homepage "https://github.com/dustinblackman/languagetool-code-comments"
  version "0.1.2"

  on_macos do
    url "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.1.2/languagetool-code-comments_0.1.2_darwin_amd64.tar.gz"
    sha256 "f992a3dea591e0b75e4a35774e51cafaea8e0362fd3944f07e6471ec63193a41"

    def install
      # Install languagetool-code-comments
      bin.install "languagetool-code-comments"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
      (bash_completion/"languagetool-code-comments").write output

      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
      (zsh_completion/"_languagetool-code-comments").write output

      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
      (fish_completion/"languagetool-code-comments.fish").write output
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the LanguagetoolCodeComments
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.1.2/languagetool-code-comments_0.1.2_linux_amd64.tar.gz"
      sha256 "792febe22d1853819c2aa1b3c754f461b75cfd3cd044fdfcdafb42798b479645"

      def install
        # Install languagetool-code-comments
        bin.install "languagetool-code-comments"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
        (bash_completion/"languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
        (zsh_completion/"_languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
        (fish_completion/"languagetool-code-comments.fish").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dustinblackman/languagetool-code-comments/releases/download/v0.1.2/languagetool-code-comments_0.1.2_linux_arm64.tar.gz"
      sha256 "02b87936603ab070b1f400b09ae2c097d8d7a2f649b5454875493786408ef259"

      def install
        # Install languagetool-code-comments
        bin.install "languagetool-code-comments"

        # Install shell completions
        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
        (bash_completion/"languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
        (zsh_completion/"_languagetool-code-comments").write output

        output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
        (fish_completion/"languagetool-code-comments.fish").write output
      end
    end
  end

  test do
    system "#{bin}/languagetool-code-comments --version"
  end
end
