# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oatmeal < Formula
  desc "Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!"
  homepage "https://github.com/dustinblackman/oatmeal"
  version "0.12.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.2/oatmeal_0.12.2_darwin_arm64.tar.gz"
      sha256 "1c1c8e98d1043aeb9ad3501939f026fdb5a29447256e1b9fe1d2637178bbded9"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.2/oatmeal_0.12.2_darwin_amd64.tar.gz"
      sha256 "a981ba28048e730cfd0d6c10aa70b39fe6a795c1caf7d302f7dddb088050782e"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.2/oatmeal_0.12.2_linux_arm64.tar.gz"
      sha256 "57f0e85d5648ba19b9a661d44e63b93d92799efdce5bef5e175c4b6d207f5d03"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.2/oatmeal_0.12.2_linux_amd64.tar.gz"
      sha256 "9c19c193c902b77a105c312e744add587440937ca5e5fe66e4c64e79d2b7c8dc"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
  end

  test do
    system "#{bin}/oatmeal --version"
  end
end
