# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oatmeal < Formula
  desc "Terminal UI to chat with large language models (LLM) using backends such as Ollama, and direct integrations with your favourite editor like Neovim!"
  homepage "https://github.com/dustinblackman/oatmeal"
  version "0.12.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.3/oatmeal_0.12.3_darwin_arm64.tar.gz"
      sha256 "6ef8c9fa2960faaae81cccc59565ff4937a830e97e5d8b81040931917d895dab"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.3/oatmeal_0.12.3_darwin_amd64.tar.gz"
      sha256 "d143050d17661445e11defa8d86c12480591ab87ba6aae1bee51efd7270b71f6"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.3/oatmeal_0.12.3_linux_arm64.tar.gz"
      sha256 "8dd4caa54f977c93b6d728a87b4ed4ff69e67e6e251836c1d9c208ecacd79e62"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dustinblackman/oatmeal/releases/download/v0.12.3/oatmeal_0.12.3_linux_amd64.tar.gz"
      sha256 "04852d1e298dfc7934673fb00cbcc75c63d39c65e63b88c3bcc0411a73bae179"

      def install
        bin.install "oatmeal"
        bash_completion.install "completions/oatmeal.bash" => "oatmeal"
        zsh_completion.install "completions/oatmeal.zsh" => "_oatmeal"
        fish_completion.install "completions/oatmeal.fish"
        man1.install "manpages/oatmeal.1.gz"
      end
    end
  end

  test do
    system "#{bin}/oatmeal --version"
  end
end
